import os
import time
import json
import tempfile
from pathlib import Path
from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from fastapi.responses import FileResponse, JSONResponse
from typing import List, Optional, Dict
import subprocess

BASE_DIR = Path(__file__).resolve().parent.parent
VIDEO_OUT_DIR = BASE_DIR / "output_videos"
VIDEO_OUT_DIR.mkdir(parents=True, exist_ok=True)
LIBRARY_AUDIO_DIR = BASE_DIR / "library_audio"
TEMP_DIR = Path(tempfile.gettempdir())

router = APIRouter(prefix="/api/ffmpeg", tags=["FFmpeg Studio"])

# Global dictionary to store progress
# Note: In production with multiple workers, this should be Redis/Database
srt_progress: Dict[str, int] = {}

# Import speech-to-text module
try:
    from speech_to_text import audio_to_srt
    SPEECH_MODULE_AVAILABLE = True
except ImportError:
    SPEECH_MODULE_AVAILABLE = False
    print("[FFmpeg] speech_to_text module not available")


@router.get("/srt_progress/{task_id}")
async def get_srt_progress(task_id: str):
    """Check the progress of an SRT generation task"""
    prog = srt_progress.get(task_id, 0)
    return {"progress": prog}


@router.get("/generate_srt")
def generate_srt(audio_url: str = None, audio_filename: str = None, language: str = "vi-VN", task_id: str = None):
    """Generate SRT subtitle file using free Speech Recognition"""
    try:
        # Determine audio path
        if audio_url:
            # From library
            audio_filename = Path(audio_url).name
            audio_path = LIBRARY_AUDIO_DIR / audio_filename
        elif audio_filename:
            # From temp upload (generated by frontend)
            audio_path = Path(tempfile.gettempdir()) / audio_filename
        else:
            raise HTTPException(status_code=400, detail="No audio provided")

        if not audio_path.exists():
            raise HTTPException(status_code=404, detail=f"Audio file not found: {audio_path}")

        # Get audio duration
        cmd_probe = [
            "ffprobe", "-v", "error", "-show_entries", "format=duration",
            "-of", "json", str(audio_path)
        ]
        result = subprocess.run(cmd_probe, capture_output=True, text=True, timeout=30)
        audio_info = json.loads(result.stdout)
        duration = float(audio_info['format']['duration'])

        srt_content = None

        # Progress callback to update global state
        def update_progress(p):
            global srt_progress
            if task_id:
                srt_progress[task_id] = p
                # Force printing to console for debugging
                print(f"[SRT Progress Update] {task_id} -> {p}%")

        # Use unified audio_to_srt from speech_to_text module
        if SPEECH_MODULE_AVAILABLE:
            if task_id: srt_progress[task_id] = 5 # Initial kick-off
            srt_content = audio_to_srt(audio_path, language, duration, progress_callback=update_progress)

        if not srt_content:
            raise HTTPException(status_code=500, detail="Speech recognition failed and no text in metadata")

        # Save SRT file
        srt_filename = audio_path.stem + ".srt"
        srt_path = VIDEO_OUT_DIR / srt_filename
        with open(srt_path, "w", encoding="utf-8") as f:
            f.write(srt_content)

        if task_id: srt_progress[task_id] = 100
        
        return {
            "srt_content": srt_content,
            "srt_url": f"/video/output/{srt_filename}",
            "filename": srt_filename
        }
    except Exception as e:
        print(f"[FFmpeg] Error generating SRT: {e}")
        import traceback
        traceback.print_exc()
        if task_id: srt_progress[task_id] = 0
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/upload_temp_audio")
async def upload_temp_audio(audio: UploadFile = File(...)):
    """Upload audio to temp directory for SRT generation"""
    try:
        temp_path = TEMP_DIR / f"temp_audio_{int(time.time())}_{audio.filename}"
        with open(temp_path, "wb") as f:
            content = await audio.read()
            f.write(content)

        return {"filename": temp_path.name, "path": str(temp_path)}
    except Exception as e:
        print(f"[FFmpeg] Error uploading temp audio: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/list_videos")
async def list_output_videos():
    """List all videos in output directory"""
    try:
        videos = []
        for f in sorted(VIDEO_OUT_DIR.glob("*.mp4"), key=lambda x: x.stat().st_mtime, reverse=True):
            videos.append({
                "name": f.name,
                "url": f"/video/output/{f.name}",
                "size": f.stat().st_size,
                "mtime": f.stat().st_mtime,
            })
        return videos
    except Exception as e:
        print(f"[FFmpeg] Error listing videos: {e}")
        return []


@router.delete("/delete_video")
async def delete_output_video(filename: str):
    """Delete a video from output directory"""
    try:
        file_path = VIDEO_OUT_DIR / filename
        if file_path.exists():
            file_path.unlink()
            return {"success": True, "message": f"Deleted {filename}"}
        return {"success": False, "message": "File not found"}
    except Exception as e:
        print(f"[FFmpeg] Error deleting video: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/update_srt")
async def update_srt(filename: str = Form(...), content: str = Form(...)):
    """Update an existing SRT file with new content"""
    try:
        srt_path = VIDEO_OUT_DIR / filename
        if not srt_path.name.endswith(".srt"):
             raise HTTPException(status_code=400, detail="Invalid SRT filename")
             
        with open(srt_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        return {"success": True, "message": f"Updated {filename}"}
    except Exception as e:
        print(f"[FFmpeg] Error updating SRT: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate")
async def generate_video_ffmpeg(
    videos: List[UploadFile] = File(...),
    audio: UploadFile = File(None),
    audio_url: str = Form(None),
    include_srt: str = Form(None),
    srt_filename: str = Form(None), # Allow using pre-generated/edited SRT
    language: str = Form("vi-VN"), # Added language selection
    loop_count: int = Form(1),
    aspect_ratio: str = Form('16:9'),
    font_size: int = Form(24), # Allow customizing subtitle size
    subtitle_margin: int = Form(20), # Allow customizing subtitle vertical position
):
    """Generate video using FFmpeg - auto-loop videos to match audio length, then trim"""
    video_filename = f"ffmpeg_video_{int(time.time())}.mp4"
    output_path = VIDEO_OUT_DIR / video_filename

    try:
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            video_paths = []
            processed_paths = []

            # Save uploaded videos
            for i, video in enumerate(videos):
                video_path = tmpdir_path / f"video_{i}_{video.filename}"
                with open(video_path, "wb") as f:
                    content = await video.read()
                    f.write(content)
                video_paths.append(video_path)

            # Save audio - either from upload or from library URL
            if audio and audio.filename:
                audio_path = tmpdir_path / audio.filename
                with open(audio_path, "wb") as f:
                    content = await audio.read()
                    f.write(content)
            elif audio_url:
                # Extract filename from URL and copy from library
                audio_filename = Path(audio_url).name
                library_audio_path = BASE_DIR / "library_audio" / audio_filename
                if not library_audio_path.exists():
                    raise HTTPException(status_code=404, detail=f"Audio file not found in library: {audio_filename}")
                audio_path = tmpdir_path / audio_filename
                import shutil
                shutil.copy2(library_audio_path, audio_path)
            else:
                raise HTTPException(status_code=400, detail="No audio provided. Please upload audio or select from library.")

            # Get audio duration
            cmd_probe_audio = [
                "ffprobe", "-v", "error", "-show_entries", "format=duration",
                "-of", "json", str(audio_path)
            ]
            result = subprocess.run(cmd_probe_audio, capture_output=True, text=True, timeout=30)
            audio_info = json.loads(result.stdout)
            audio_duration = float(audio_info['format']['duration'])
            print(f"[FFmpeg] Audio duration: {audio_duration}s")

            # Target dimensions
            if aspect_ratio == '9:16':
                target_w, target_h = 1080, 1920
            else:
                target_w, target_h = 1920, 1080
            print(f"[FFmpeg] Target: {target_w}x{target_h}")

            # Process each video for aspect ratio and resolution normalization
            for idx, vp in enumerate(video_paths):
                cmd_probe_v = [
                    "ffprobe", "-v", "error", "-select_streams", "v:0",
                    "-show_entries", "stream=width,height", "-of", "json", str(vp)
                ]
                result = subprocess.run(cmd_probe_v, capture_output=True, text=True, timeout=30)
                v_info = json.loads(result.stdout)
                v_stream = v_info['streams'][0]
                v_w, v_h = int(v_stream['width']), int(v_stream['height'])
                print(f"[FFmpeg] Video {idx}: {v_w}x{v_h}")

                processed = tmpdir_path / f"processed_{idx}.mp4"
                target_ratio = target_w / target_h
                video_ratio = v_w / v_h

                # Calculate dimensions to fit inside target while maintaining ratio
                if video_ratio > target_ratio:
                    new_w, new_h = target_w, int(target_w / video_ratio)
                else:
                    new_w, new_h = int(target_h * video_ratio), target_h
                
                # Make dimensions even for libx264
                new_w = (new_w // 2) * 2
                new_h = (new_h // 2) * 2

                # ALWAYS normalize to target_w x target_h with blur background to prevent stretching
                # and ensure all segments have IDENTICAL resolution for concatenation
                filter_complex = (
                    f"[0:v]scale={target_w}:{target_h},boxblur=20[bg];"
                    f"[0:v]scale={new_w}:{new_h}[fg];"
                    f"[bg][fg]overlay=(W-w)/2:(H-h)/2,setsar=1[out]"
                )

                cmd = [
                    "ffmpeg", "-y", "-i", str(vp),
                    "-filter_complex", filter_complex,
                    "-map", "[out]", "-map", "0:a?",
                    "-c:v", "libx264", "-preset", "ultrafast",
                    "-c:a", "aac", "-b:a", "128k",
                    "-pix_fmt", "yuv420p", # Ensure consistent pixel format
                    "-r", "30",            # Force consistent frame rate
                    str(processed)
                ]

                print(f"[FFmpeg] Normalizing video {idx} to {target_w}x{target_h}")
                subprocess.run(cmd, capture_output=True, text=True, timeout=300)
                processed_paths.append(processed)

            # Concatenate all processed videos
            concat_file = tmpdir_path / "concat.txt"
            with open(concat_file, "w") as f:
                for pp in processed_paths:
                    f.write(f"file '{pp}'\n")

            concat_output = tmpdir_path / "concatenated.mp4"
            cmd_concat = [
                "ffmpeg", "-y",
                "-f", "concat", "-safe", "0", "-i", str(concat_file),
                "-c", "copy",
                str(concat_output)
            ]
            print(f"[FFmpeg] Concatenating videos")
            subprocess.run(cmd_concat, capture_output=True, text=True, timeout=600)

            # Get concatenated duration
            result = subprocess.run(
                ["ffprobe", "-v", "error", "-show_entries", "format=duration",
                 "-of", "json", str(concat_output)],
                capture_output=True, text=True, timeout=30
            )
            concat_info = json.loads(result.stdout)
            concat_duration = float(concat_info['format']['duration'])
            print(f"[FFmpeg] Concatenated: {concat_duration}s, Need: {audio_duration}s")

            # Loop if needed
            final_video = concat_output
            if concat_duration < audio_duration or loop_count > 1:
                if loop_count > 1:
                    loops_needed = loop_count
                else:
                    loops_needed = int(audio_duration / concat_duration) + 1

                print(f"[FFmpeg] Looping {loops_needed} times")
                loop_concat = tmpdir_path / "loop_concat.txt"
                with open(loop_concat, "w") as f:
                    for _ in range(loops_needed):
                        f.write(f"file '{concat_output}'\n")

                final_video = tmpdir_path / "looped.mp4"
                cmd_loop = [
                    "ffmpeg", "-y",
                    "-f", "concat", "-safe", "0", "-i", str(loop_concat),
                    "-c", "copy",
                    str(final_video)
                ]
                subprocess.run(cmd_loop, capture_output=True, text=True, timeout=600)

            # Generate/Load SRT if requested
            srt_path = None
            if srt_filename:
                # Use existing SRT file from VIDEO_OUT_DIR
                existing_srt = VIDEO_OUT_DIR / srt_filename
                if existing_srt.exists():
                    srt_path = tmpdir_path / srt_filename
                    import shutil
                    shutil.copy2(existing_srt, srt_path)
                    print(f"[FFmpeg] Using existing SRT: {srt_path}")
                else:
                    print(f"[FFmpeg] Requested SRT not found: {existing_srt}")
            
            elif include_srt and include_srt.lower() == 'true':
                try:
                    if SPEECH_MODULE_AVAILABLE:
                        # Use the requested language
                        srt_content = audio_to_srt(audio_path, language, audio_duration)

                        if srt_content:
                            srt_path = tmpdir_path / (Path(audio_path).stem + ".srt")
                            with open(srt_path, "w", encoding="utf-8") as f:
                                f.write(srt_content)
                            print(f"[FFmpeg] Generated SRT ({language}): {srt_path}")
                        else:
                            print("[FFmpeg] audio_to_srt returned no content")
                except Exception as e:
                    print(f"[FFmpeg] Error generating SRT: {e}")
                    import traceback
                    traceback.print_exc()

            # Build final FFmpeg command
            filter_parts = []
            output_map = "[0:v]" # Default video stream from final_video

            if srt_path and srt_path.exists() and srt_path.stat().st_size > 0:
                # FFmpeg subtitles filter on Windows needs path escaping (colons and backslashes)
                # The most robust way: replace \ with / and escape : as \:
                # IMPORTANT: In Python strings, \\: becomes \: which FFmpeg needs
                escaped_srt_path = str(srt_path).replace("\\", "/").replace(":", "\\:")
                
                # Use a simpler style first to ensure it works
                # MarginV controls the vertical distance from the bottom/top
                style_str = f"FontSize={font_size},PrimaryColour=&H00FFFFFF,Alignment=2,Outline=1,Shadow=1,MarginV={subtitle_margin}"
                
                # Construct the filter
                filter_parts.append(f"subtitles='{escaped_srt_path}':force_style='{style_str}'")
                output_map = "[out_v]"
                
                # Combine filters if we had more, but for now just subtitles
                filter_complex = f"[0:v]{filter_parts[0]}[out_v]"
                
                cmd_final = [
                    "ffmpeg", "-y",
                    "-i", str(final_video),
                    "-i", str(audio_path),
                    "-filter_complex", filter_complex,
                    "-map", "[out_v]", "-map", "1:a:0",
                    "-c:v", "libx264", "-preset", "ultrafast",
                    "-c:a", "aac", "-b:a", "128k",
                    "-t", str(audio_duration),
                    str(output_path)
                ]
            else:
                print("[FFmpeg] No valid SRT found, generating video without subtitles")
                cmd_final = [
                    "ffmpeg", "-y",
                    "-i", str(final_video),
                    "-i", str(audio_path),
                    "-c:v", "libx264", "-preset", "ultrafast",
                    "-c:a", "aac", "-b:a", "128k",
                    "-map", "0:v:0", "-map", "1:a:0",
                    "-t", str(audio_duration),
                    str(output_path)
                ]

            print(f"[FFmpeg] Executing: {' '.join(cmd_final)}")
            print(f"[FFmpeg] Final: adding audio + trim to {audio_duration}s")
            result = subprocess.run(cmd_final, capture_output=True, text=True, timeout=600)

            if result.returncode != 0:
                print(f"[FFmpeg] Error: {result.stderr}")
                raise HTTPException(status_code=500, detail=f"FFmpeg error: {result.stderr}")

            print(f"[FFmpeg] Success: {output_path}")

        return {"status": "success", "url": f"/video/output/{video_filename}"}

    except Exception as e:
        print(f"[FFmpeg] Exception: {str(e)}")
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))
